argocd:
  clusterName: my-cluster
  namespace: argocd
  cluster: https://kubernetes.default.svc
  project: default

kyverno:
  enabled: true
  chart: 
    repository: https://kyverno.github.io/kyverno/
    name: kyverno
    version: 3.2.7
  namespace: kyverno



